import { strict as assert } from "node:assert";
import { pickCaptionTrack } from "@modules/lyrics/providers/ytCaptions";

const track = (languageCode: string, autoGenerated = false) => ({
  languageCode,
  displayName: autoGenerated ? `${languageCode} (auto-generated)` : languageCode,
});

// -- Script-aware pick --------------------------

assert.equal(pickCaptionTrack([track("zh-CN"), track("zh-TW")], "zh-TW")?.languageCode, "zh-TW");
assert.equal(pickCaptionTrack([track("zh-TW"), track("zh-CN")], "zh-CN")?.languageCode, "zh-CN");
assert.equal(pickCaptionTrack([track("zh-Hans"), track("zh-Hant")], "zh-TW")?.languageCode, "zh-Hant");
assert.equal(pickCaptionTrack([track("en-GB"), track("en")], "en")?.languageCode, "en");

// -- Loose fallback keeps captions loading --------------------------

assert.equal(pickCaptionTrack([track("en-US")], "en")?.languageCode, "en-US");
assert.equal(pickCaptionTrack([track("ko-KR")], "ko")?.languageCode, "ko-KR");
assert.equal(pickCaptionTrack([track("zh-CN")], "zh-TW")?.languageCode, "zh-CN");
assert.equal(pickCaptionTrack([track("sr-Latn")], "sr")?.languageCode, "sr-Latn");

// -- Auto-generated tracks are never picked --------------------------

assert.equal(pickCaptionTrack([track("zh-TW", true), track("zh-CN")], "zh-TW")?.languageCode, "zh-CN");
assert.equal(pickCaptionTrack([track("en", true)], "en"), undefined);

// -- Edge cases --------------------------

assert.equal(pickCaptionTrack([], "en"), undefined);
assert.equal(pickCaptionTrack([track("fr"), track("de")], "en"), undefined);

// -- Invariants --------------------------

const tracks = [track("zh-CN"), track("zh-TW"), track("en")];
const snapshot = structuredClone(tracks);
for (const code of ["zh-TW", "zh-CN", "en", "ja"]) {
  const picked = pickCaptionTrack(tracks, code);
  assert.ok(picked === undefined || tracks.includes(picked));
}
assert.deepEqual(tracks, snapshot);

console.log("ytCaptions self-check passed");
